### PR TITLE
Make the ISO building fix in the CI script

### PR DESCRIPTION
**Pull request by ct-martin**

### CODE REVIEW

**Comment by ct-martin** [comment]
(cc @axk4545 )

**Comment by axk4545** [comment]
@ct-martin still failed. at some point I probably need to offload the files on the builder and do a clean install. Maybe when we do the automation.

**Comment by ct-martin** [comment]
@axk4545 are you on the mock nightly/latest?

**Comment by axk4545** [comment]
This is the output of mock pn the builder: mock.py version 1.4.6 starting (python version = 3.6.2)

**Pull request closed without merging**
