### PR TITLE
Added the requested licensing section to the README.md.

### LINKED ISSUE #141: Make Licensing clear for the design assets in our README and Wiki
# Summary

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [x] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: 
Documentation fixes to make it clear the licensing for our design assets.

# Details

Currently we do not have the Creative Commons Licensing for the design assets clearly stated anywhere. I believe we should have a Licensing section either in the README for the main repo or in each of the 2 design assets repos we have. I also want to add a section on the TigerOS Design wiki page that denotes the licensing there. Do we want to force those who contribute a design that it falls under a certain license or the same license? I think we should probably require that it be some form of free of use license at least for non-commercial use.

~I believe the licensing we used was CC-BY 4.0 and we lost the documentation somewhere when we did the repo re-organization.~ It's CC-BY-SA 4.0 I found it in the [commit history](https://github.com/RITlug/TigerOS/blob/1ed37e8e96c12e3083fd3e2afd146db5ed2f43cf/sources/tigeros-backgrounds/tigeros-backgrounds-1.0/LICENSE).

This is related to issue #137 but I wanted to separate it as it's more than just the README.

Thoughts?

### PR DESCRIPTION
**Pull request by eza5640**
# Summary

* This is a…
    * [ ] Bug fix
    * [X] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:
I added a licensing section to the README.md, as requested on the fedora 'easy-fix' page. This is being completed for a bugfix assignment in one of my classes here at RIT.

# Problem

* **GitHub issue** (_optional_): 
The README.md does not reflect the appropriate licensing for the design assets in the repository.

# Solution

The addition includes a link to the specified folder with the design assets within, and details the clauses with redistribution and remixing of the original content.

# Action

### CODE REVIEW

**Review by jrtechs — COMMENTED** [review]
Looks good @eza5640. I believe this closes #141?

**Comment by Tjzabel** [comment]
@eza5640 hello! :wave: 

This looks good to me. My only issue is that development of TigerOS has moved to [GitLab](https://gitlab.com/RITlug/TigerOS), but that is okay with the scope of this PR. 

May I ask what you mean by this being on the fedora "easy-fix" page?

**Comment by justwheel** [comment]
> May I ask what you mean by this being on the fedora "easy-fix" page?

It's listed on the Fedora Project easyfix page here:

https://fedoraproject.org/easyfix/#RITlug/TigerOS

It might be worth updating the Fedora crawler to look at TigerOS's GitLab instead:

https://fedoraproject.org/wiki/Easyfix

**Comment by Tjzabel** [comment]
@jwflory ah, thanks! I wasn't aware we were on there as an easy-fix :sweat_smile:

**Pull request merged**
